package ai.phasechange.gherkin.ast

interface AstVisitor {
    fun visit(anything: GherkinAnything)
    fun visit(background: GherkinBackground)
    fun visit(backgroundLine: GherkinBackgroundLine)
    fun visit(description: GherkinDescription)
    fun visit(dataTable: GherkinDataTable)
    fun visit(descriptionHelper: GherkinDescriptionHelper)
    fun visit(doc: GherkinDocument)
    fun visit(docString: GherkinDocString)
    fun visit(examplesDefinition: GherkinExamplesDefinition)
    fun visit(examplesLine: GherkinExamplesLine)
    fun visit(feature: GherkinFeature)
    fun visit(featureDescHelper: GherkinFeatureDescHelper)
    fun visit(featureHeader: GherkinFeatureHeader)
    fun visit(featureLine: GherkinFeatureLine)
    fun visit(featureDesc: GherkinFeatureDesc)
    fun visit(other: GherkinOther)
    fun visit(rule: GherkinRule)
    fun visit(ruleHeader: GherkinRuleHeader)
    fun visit(ruleLine: GherkinRuleLine)
    fun visit(scenario: GherkinScenario)
    fun visit(scenarioDefinition: GherkinScenarioDefinition)
    fun visit(scenarioLine: GherkinScenarioLine)
    fun visit(step: GherkinStep)
    fun visit(stepLine: GherkinStepLine)
    fun visit(stepArg: GherkinStepArg)
    fun visit(tag: GherkinTag)
    fun visit(tagline: GherkinTagline)
    fun visit(tags: GherkinTags)
}